/* SPDX-FileCopyrightText: © 2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

use core::{ffi, slice};

use gfxd_sys::ptr::NonNullConst;

use crate::{
    lib_data::LibData, Address, LookatCount, MacroInfo, MacroPrinter, Printer, TexFmt, TexSiz,
    TlutCount,
};

// 'cls is short for closure
#[allow(clippy::type_complexity)]
pub struct Customizer<'cls> {
    before_execution: Option<&'cls mut dyn FnMut(&mut Printer)>,
    after_execution: Option<&'cls mut dyn FnMut(&mut Printer)>,

    macro_fn: Option<&'cls mut dyn FnMut(&mut MacroPrinter, &mut MacroInfo) -> MacroFnRet>,
    arg_fn: Option<&'cls mut dyn FnMut(&mut MacroPrinter, &mut MacroInfo, i32)>,

    tlut_fn: Option<
        &'cls mut dyn FnMut(
            &mut Printer,
            &mut MacroInfo,
            Address,
            Option<u8>,
            TlutCount,
        ) -> DoDefaultOutput,
    >,
    timg_fn: Option<
        &'cls mut dyn FnMut(
            &mut Printer,
            &mut MacroInfo,
            Address,
            TexFmt,
            TexSiz,
            u8,
            u8,
            u8,
        ) -> DoDefaultOutput,
    >,
    cimg_fn: Option<
        &'cls mut dyn FnMut(
            &mut Printer,
            &mut MacroInfo,
            Address,
            TexFmt,
            TexSiz,
            u16,
        ) -> DoDefaultOutput,
    >,
    zimg_fn: Option<&'cls mut dyn FnMut(&mut Printer, &mut MacroInfo, Address) -> DoDefaultOutput>,
    dl_fn: Option<&'cls mut dyn FnMut(&mut Printer, &mut MacroInfo, Address) -> DoDefaultOutput>,
    mtx_fn: Option<&'cls mut dyn FnMut(&mut Printer, &mut MacroInfo, Address) -> DoDefaultOutput>,
    lookat_fn: Option<
        &'cls mut dyn FnMut(&mut Printer, &mut MacroInfo, Address, LookatCount) -> DoDefaultOutput,
    >,
    vtx_fn:
        Option<&'cls mut dyn FnMut(&mut Printer, &mut MacroInfo, Address, i32) -> DoDefaultOutput>,
    vp_fn: Option<&'cls mut dyn FnMut(&mut Printer, &mut MacroInfo, Address) -> DoDefaultOutput>,
}

impl Customizer<'_> {
    pub(crate) fn apply_callbacks(&mut self) {
        self.apply_out_callback();
        self.apply_user_macro_callbacks();
        self.apply_user_arg_callbacks();
    }

    fn apply_out_callback(&mut self) {
        // Write to an out buffer
        extern "C" fn output_callback(
            buf: NonNullConst<ffi::c_char>,
            count: ffi::c_int,
        ) -> ffi::c_int {
            // Retrieve the out_buf from the user data pointer.
            let lib_data = LibData::get().expect("Welp. Maybe race condition?");

            // SAFETY: We just have to trust the length of the data is correct.
            let raw_slice = unsafe { slice::from_raw_parts(buf.as_ptr().cast(), count as _) };

            // SAFETY: gfxd doesn't use non-ascii characters, and everything
            // else should be generated by the user, which should be UTF-8
            // already, since that's the only thing the API supports.
            let data_str = unsafe { str::from_utf8_unchecked(raw_slice) };

            // Push the output into our buffer.
            lib_data.write_to_buf(data_str);

            // We read the whole buffer.
            count
        }

        // Write the disassembly output to out_buf.
        // We pass it around by passing it as a user data pointer (LibData).
        unsafe {
            gfxd_sys::io::gfxd_output_callback(Some(output_callback));
        }
    }

    fn apply_user_macro_callbacks(&mut self) {
        if self.macro_fn.is_some() {
            extern "C" fn callback() -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().macro_fn {
                    let mut printer = MacroPrinter::new();
                    let mut info = MacroInfo::new();
                    (closure)(&mut printer, &mut info)
                } else {
                    panic!("macro_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::handlers::gfxd_macro_fn(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::handlers::gfxd_macro_fn(None);
            }
        }

        if self.arg_fn.is_some() {
            extern "C" fn callback(arg_num: ffi::c_int) {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                if let Some(closure) = &mut lib_data.get_customizer_mut().arg_fn {
                    let mut printer = MacroPrinter::new();
                    let mut info = MacroInfo::new();
                    (closure)(&mut printer, &mut info, arg_num)
                } else {
                    panic!("arg_fn closure was None?")
                }
            }
            unsafe {
                gfxd_sys::handlers::gfxd_arg_fn(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::handlers::gfxd_arg_fn(None);
            }
        }
    }

    fn apply_user_arg_callbacks(&mut self) {
        if self.tlut_fn.is_some() {
            extern "C" fn callback(tlut: u32, idx: i32, count: i32) -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().tlut_fn {
                    let mut printer = Printer::new();
                    let mut info = MacroInfo::new();
                    let timg = Address(tlut);
                    let index = if idx == -1 { None } else { Some(idx as u8) };
                    let tlut_count = TlutCount::new(count);
                    (closure)(&mut printer, &mut info, timg, index, tlut_count)
                } else {
                    panic!("tlut_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_tlut_callback(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_tlut_callback(None);
            }
        }

        if self.timg_fn.is_some() {
            extern "C" fn callback(
                timg: u32,
                fmt: i32,
                siz: i32,
                width: i32,
                height: i32,
                pal: i32,
            ) -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().timg_fn {
                    let mut printer = Printer::new();
                    let mut info = MacroInfo::new();
                    let timg = Address(timg);
                    let tex_fmt = TexFmt::new(fmt);
                    let tex_siz = TexSiz::new(siz);
                    (closure)(
                        &mut printer,
                        &mut info,
                        timg,
                        tex_fmt,
                        tex_siz,
                        width as _,
                        height as _,
                        pal as _,
                    )
                } else {
                    panic!("timg_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_timg_callback(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_timg_callback(None);
            }
        }

        if self.cimg_fn.is_some() {
            extern "C" fn callback(cimg: u32, fmt: i32, siz: i32, width: i32) -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().cimg_fn {
                    let mut printer = Printer::new();
                    let mut info = MacroInfo::new();
                    let cimg = Address(cimg);
                    let tex_fmt = TexFmt::new(fmt);
                    let tex_siz = TexSiz::new(siz);
                    (closure)(&mut printer, &mut info, cimg, tex_fmt, tex_siz, width as _)
                } else {
                    panic!("cimg_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_cimg_callback(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_cimg_callback(None);
            }
        }

        if self.zimg_fn.is_some() {
            extern "C" fn callback(zimg: u32) -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().zimg_fn {
                    let mut printer = Printer::new();
                    let mut info = MacroInfo::new();
                    let zimg = Address(zimg);
                    (closure)(&mut printer, &mut info, zimg)
                } else {
                    panic!("zimg_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_zimg_callback(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_zimg_callback(None);
            }
        }

        if self.dl_fn.is_some() {
            extern "C" fn callback(dl: u32) -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().dl_fn {
                    let mut printer = Printer::new();
                    let mut info = MacroInfo::new();
                    let dl = Address(dl);
                    (closure)(&mut printer, &mut info, dl)
                } else {
                    panic!("dl_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_dl_callback(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_dl_callback(None);
            }
        }

        if self.mtx_fn.is_some() {
            extern "C" fn callback(mtx: u32) -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().mtx_fn {
                    let mut printer = Printer::new();
                    let mut info = MacroInfo::new();
                    let mtx = Address(mtx);
                    (closure)(&mut printer, &mut info, mtx)
                } else {
                    panic!("mtx_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_mtx_callback(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_mtx_callback(None);
            }
        }

        if self.lookat_fn.is_some() {
            extern "C" fn callback(lookat: u32, count: i32) -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().lookat_fn {
                    let mut printer = Printer::new();
                    let mut info = MacroInfo::new();
                    let lookat = Address(lookat);
                    let count = LookatCount::new(count);
                    (closure)(&mut printer, &mut info, lookat, count)
                } else {
                    panic!("lookat_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_lookat_callback(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_lookat_callback(None);
            }
        }

        if self.vtx_fn.is_some() {
            extern "C" fn callback(vtx: u32, num: i32) -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().vtx_fn {
                    let mut printer = Printer::new();
                    let mut info = MacroInfo::new();
                    let vtx = Address(vtx);
                    (closure)(&mut printer, &mut info, vtx, num)
                } else {
                    panic!("vtx_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_vtx_callback(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_vtx_callback(None);
            }
        }

        if self.vp_fn.is_some() {
            extern "C" fn callback(vp: u32) -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().vp_fn {
                    let mut printer = Printer::new();
                    let mut info = MacroInfo::new();
                    let vp = Address(vp);
                    (closure)(&mut printer, &mut info, vp)
                } else {
                    panic!("vp_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_vp_callback(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_vp_callback(None);
            }
        }
    }
}

impl Customizer<'_> {
    pub const fn new() -> Self {
        Self {
            before_execution: None,
            after_execution: None,
            macro_fn: None,
            arg_fn: None,
            tlut_fn: None,
            timg_fn: None,
            cimg_fn: None,
            zimg_fn: None,
            dl_fn: None,
            mtx_fn: None,
            lookat_fn: None,
            vtx_fn: None,
            vp_fn: None,
        }
    }
}

impl<'cls> Customizer<'cls> {
    pub fn before_after_execution_callback<B, A>(&mut self, before: &'cls mut B, after: &'cls mut A)
    where
        B: FnMut(&mut Printer),
        A: FnMut(&mut Printer),
    {
        self.before_execution = Some(before);
        self.after_execution = Some(after);
    }

    pub(crate) fn do_before(&mut self) {
        if let Some(closure) = &mut self.before_execution {
            let mut printer = Printer::new();
            (closure)(&mut printer);
        }
    }
    pub(crate) fn do_after(&mut self) {
        if let Some(closure) = &mut self.after_execution {
            let mut printer = Printer::new();
            (closure)(&mut printer);
        }
    }
}

impl<'cls> Customizer<'cls> {
    pub fn macro_fn<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut MacroPrinter, &mut MacroInfo) -> MacroFnRet,
    {
        self.macro_fn = Some(callback);
    }

    pub fn arg_fn<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut MacroPrinter, &mut MacroInfo, i32),
    {
        self.arg_fn = Some(callback);
    }
}

impl<'cls> Customizer<'cls> {
    pub fn tlut_callback<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut Printer, &mut MacroInfo, Address, Option<u8>, TlutCount) -> DoDefaultOutput,
    {
        self.tlut_fn = Some(callback);
    }

    pub fn timg_callback<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(
            &mut Printer,
            &mut MacroInfo,
            Address,
            TexFmt,
            TexSiz,
            u8,
            u8,
            u8,
        ) -> DoDefaultOutput,
    {
        self.timg_fn = Some(callback);
    }

    pub fn cimg_callback<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut Printer, &mut MacroInfo, Address, TexFmt, TexSiz, u16) -> DoDefaultOutput,
    {
        self.cimg_fn = Some(callback);
    }

    pub fn zimg_callback<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut Printer, &mut MacroInfo, Address) -> DoDefaultOutput,
    {
        self.zimg_fn = Some(callback);
    }

    pub fn dl_callback<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut Printer, &mut MacroInfo, Address) -> DoDefaultOutput,
    {
        self.dl_fn = Some(callback);
    }

    pub fn mtx_callback<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut Printer, &mut MacroInfo, Address) -> DoDefaultOutput,
    {
        self.mtx_fn = Some(callback);
    }

    pub fn lookat_callback<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut Printer, &mut MacroInfo, Address, LookatCount) -> DoDefaultOutput,
    {
        self.lookat_fn = Some(callback);
    }

    pub fn vtx_callback<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut Printer, &mut MacroInfo, Address, i32) -> DoDefaultOutput,
    {
        self.vtx_fn = Some(callback);
    }

    pub fn vp_callback<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut Printer, &mut MacroInfo, Address) -> DoDefaultOutput,
    {
        self.vp_fn = Some(callback);
    }
}

impl<'cls> Default for Customizer<'cls> {
    fn default() -> Self {
        Self::new()
    }
}

pub enum DoDefaultOutput {
    DoDefault,
    Override,
}

impl DoDefaultOutput {
    #[inline]
    pub(crate) const fn into_ret(self) -> ffi::c_int {
        match self {
            Self::DoDefault => 0,
            Self::Override => 1,
        }
    }
}

pub enum MacroFnRet {
    Continue,
    Stop,
}

impl MacroFnRet {
    #[inline]
    pub(crate) const fn into_ret(self) -> ffi::c_int {
        match self {
            Self::Continue => 0,
            Self::Stop => 1,
        }
    }
}
