/* SPDX-FileCopyrightText: © 2025 Decompollaborate */
/* SPDX-License-Identifier: MIT */

use core::{ffi, slice};

use gfxd_sys::ptr::NonNullConst;

use crate::{lib_data::LibData, Printer};

// 'cls is short for closure
#[allow(clippy::type_complexity)]
pub struct Customizer<'cls> {
    before_execution: Option<&'cls mut dyn FnMut(&mut Printer)>,
    after_execution: Option<&'cls mut dyn FnMut(&mut Printer)>,

    // tlut_fn: Option<Box<dyn FnMut(&Printer, u32, i32, i32) -> DoDefaultOutput>>,
    vtx_fn: Option<&'cls mut dyn FnMut(&mut Printer, u32, i32) -> DoDefaultOutput>,
}

impl<'cls> Customizer<'cls> {
    pub const fn new() -> Self {
        Self {
            before_execution: None,
            after_execution: None,
            // tlut_fn: None,
            vtx_fn: None,
        }
    }

    pub(crate) fn apply_callbacks(&mut self) {
        self.apply_out_callback();
        self.apply_user_callbacks();
    }

    fn apply_out_callback(&mut self) {
        // Write to an out buffer
        extern "C" fn output_callback(
            buf: NonNullConst<ffi::c_char>,
            count: ffi::c_int,
        ) -> ffi::c_int {
            // Retrieve the out_buf from the user data pointer.
            let lib_data = LibData::get().expect("Welp. Maybe race condition?");

            // SAFETY: We just have to trust the length of the data is correct.
            let raw_slice = unsafe { slice::from_raw_parts(buf.as_ptr().cast(), count as _) };

            // SAFETY: gfxd doesn't use non-ascii characters, and everything
            // else should be generated by the user, which should be UTF-8
            // already, since that's the only thing the API supports.
            let data_str = unsafe { str::from_utf8_unchecked(raw_slice) };

            // Push the output into our buffer.
            lib_data.write_to_buf(data_str);

            // We read the whole buffer.
            count
        }

        // Write the disassembly output to out_buf.
        // We pass it around by passing it as a user data pointer (LibData).
        unsafe {
            gfxd_sys::io::gfxd_output_callback(Some(output_callback));
        }
    }

    fn apply_user_callbacks(&mut self) {
        if self.vtx_fn.is_some() {
            extern "C" fn callback(vtx: u32, num: i32) -> ffi::c_int {
                let lib_data = LibData::get().expect("Welp. Maybe race condition?");

                let ret = if let Some(closure) = &mut lib_data.get_customizer_mut().vtx_fn {
                    let mut printer = Printer::new();
                    (closure)(&mut printer, vtx, num)
                } else {
                    panic!("vtx_fn closure was None?")
                };

                ret.into_ret()
            }
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_vtx_callback(Some(callback));
            }
        } else {
            unsafe {
                gfxd_sys::argument_callbacks::gfxd_vtx_callback(None);
            }
        }
    }

    pub fn before_after_execution_callback<B, A>(&mut self, before: &'cls mut B, after: &'cls mut A)
    where
        B: FnMut(&mut Printer),
        A: FnMut(&mut Printer),
    {
        self.before_execution = Some(before);
        self.after_execution = Some(after);
    }

    pub(crate) fn do_before(&mut self) {
        if let Some(closure) = &mut self.before_execution {
            let mut printer = Printer::new();
            (closure)(&mut printer);
        }
    }
    pub(crate) fn do_after(&mut self) {
        if let Some(closure) = &mut self.after_execution {
            let mut printer = Printer::new();
            (closure)(&mut printer);
        }
    }

    /*
    pub fn tlut_callback<F>(&mut self, callback: F)
    where
        F: FnMut(&Printer, u32, i32, i32) -> DoDefaultOutput + 'static,
    {
        self.tlut_fn = Some(Box::new(callback));
    }
    */

    pub fn vtx_callback<F>(&mut self, callback: &'cls mut F)
    where
        F: FnMut(&mut Printer, u32, i32) -> DoDefaultOutput,
    {
        self.vtx_fn = Some(callback);
    }
}

impl<'cls> Default for Customizer<'cls> {
    fn default() -> Self {
        Self::new()
    }
}

pub enum DoDefaultOutput {
    DoDefault,
    Override,
}

impl DoDefaultOutput {
    #[inline]
    pub(crate) const fn into_ret(self) -> ffi::c_int {
        match self {
            DoDefaultOutput::DoDefault => 0,
            DoDefaultOutput::Override => 1,
        }
    }
}
